### ISSUE TITLE
Origins incompatible with ecotones mod

### ISSUE THREAD

**Issue by asb43** [SuperCoder7979/ecotones#18] opened 2021-07-21 05:06 UTC
upon starting up my copy of the AOF4 modpack where I added a few mods including origins (and 3 of its addon mods), I found that I couldn't start the game. I messed around with all the mods I added but it wasn't till I removed origins that I could launch and play the game again. I know origins works without ecotones, and vice versa, but together the game won't even launch. here is the log with the issue. Not sure why this is the error but in case this can help someone figure it out then I hope this helps.

Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
at net.minecraft.class_310.method_1523(class_310.java:1103)
at net.minecraft.class_310.method_1514(class_310.java:728)
at net.minecraft.client.main.Main.main(Main.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector applyEcotonesFancyFog(F)V in ecotones.mixins.json:client.MixinBackgroundRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap ecotones-refmap.json
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
... 16 more

I also posted this in the github of the origins mod (https://github.com/apace100/origins-fabric/issues/392)

**Comment by TehcJS** [comment] 2021-07-21 12:53
This looks like a redirect conflict. What version of Fabric Loader, Fabric API, Minecraft, Ecotones, and Origins are you using?

**Comment by TehcJS** [comment] 2021-07-21 14:14
I've reproduced this bug with the latest release of Origins 1.0.3 and Ecotones 0.8.0 (1.17.1)
https://paste.ee/p/JbJic

**Comment by TehcJS** [comment] 2021-07-21 14:45
This is actually an issue with apoli: one of Origins's dependencies.
https://paste.ee/p/4cmuc

**Comment by asb43** [comment] 2021-07-21 15:19
here is the full code for the issue as for my origins and ecotones my versions are the same as yours and my fabric API is 11.6
none of my code mentions an issue with apoli so I'm not sure if that is the same problem, I notice your error says fogStart my error says FancyFog(F)V, I could be wrong but it seems like different errors, I also notice you are running on a Linux which might need different things then my Windows Pc needs but that's just a theory. The best way to recreate the error would be to install curseforge's app, then put origins into the mod file. I have a couple of other mods I added in there but they aren't the problem here so I don't see the need to mention them.

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_310.method_1523(class_310.java:1103)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector applyEcotonesFancyFog(F)V in ecotones.mixins.json:client.MixinBackgroundRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap ecotones-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more

**Comment by TehcJS** [comment] 2021-07-21 16:08
A fix for this is coming in 0.8.1 soon. In the meantime, you can download the jar on my fork of Ecotones to use it with Origins. https://github.com/CursedMC/ecotones/releases/tag/0.8.1

**Comment by SuperCoder7979** [comment] 2021-07-27 19:57
Should be fixed with 0.8.1!

**Closed by SuperCoder7979** 2021-07-27 19:57 UTC
